// Code generated by 'yaegi extract git.dbyte.xyz/distro/gerry/shared'. DO NOT EDIT.

package symbols

import (
	"git.dbyte.xyz/distro/gerry/shared"
	"reflect"
)

func init() {
	Symbols["git.dbyte.xyz/distro/gerry/shared/shared"] = map[string]reflect.Value{
		// type definitions
		"Config": reflect.ValueOf((*shared.Config)(nil)),
	}
}
