// Code generated by 'yaegi extract git.dbyte.xyz/distro/gerry/shared'. DO NOT EDIT.

package symbols

import (
	"git.dbyte.xyz/distro/gerry/shared"
	"reflect"
)

func init() {
	Symbols["git.dbyte.xyz/distro/gerry/shared/shared"] = map[string]reflect.Value{
		// type definitions
		"Bot":             reflect.ValueOf((*shared.Bot)(nil)),
		"Config":          reflect.ValueOf((*shared.Config)(nil)),
		"MessageContext":  reflect.ValueOf((*shared.MessageContext)(nil)),
		"PluginCallFunc":  reflect.ValueOf((*shared.PluginCallFunc)(nil)),
		"PluginRunFunc":   reflect.ValueOf((*shared.PluginRunFunc)(nil)),
		"PluginSetupFunc": reflect.ValueOf((*shared.PluginSetupFunc)(nil)),

		// interface wrapper definitions
		"_Bot": reflect.ValueOf((*_git_dbyte_xyz_distro_gerry_shared_Bot)(nil)),
	}
}

// _git_dbyte_xyz_distro_gerry_shared_Bot is an interface wrapper for Bot type
type _git_dbyte_xyz_distro_gerry_shared_Bot struct {
	IValue    interface{}
	WRegister func(command string, f func(bot shared.Bot, context shared.MessageContext, arguments []string, config shared.Config) error)
	WSend     func(target string, message string)
}

func (W _git_dbyte_xyz_distro_gerry_shared_Bot) Register(command string, f func(bot shared.Bot, context shared.MessageContext, arguments []string, config shared.Config) error) {
	W.WRegister(command, f)
}
func (W _git_dbyte_xyz_distro_gerry_shared_Bot) Send(target string, message string) {
	W.WSend(target, message)
}
