name: Go Test

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version-file: ./go.mod
          cache: true

      - name: Run tests
        run: go test ./...
